package com.ecommerce.product.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * 📦 PRODUCT ENTITY - The Database Model
 * 
 * Represents a product in our e-commerce catalog.
 * 
 * Fields explained:
 * - id: Unique identifier (auto-generated by MongoDB)
 * - name: Product name (e.g., "Laptop", "T-Shirt")
 * - description: Detailed product description
 * - price: Use BigDecimal for money (NEVER use double for currency!)
 * - stock: Available quantity in warehouse
 * - category: Product category for filtering
 * - sku: Stock Keeping Unit (unique product code)
 * 
 * Why BigDecimal for price?
 * double/float can have rounding errors!
 * 0.1 + 0.2 = 0.30000000000000004 ❌
 * BigDecimal handles money calculations accurately ✅
 */
@Document(collection = "products")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    
    @Id
    private String id;
    
    @Indexed(unique = true)
    private String sku;  // Unique product code (e.g., "LAP-001")
    
    private String name;
    private String description;
    private BigDecimal price;
    private Integer stock;  // Available quantity
    private String category;
    private String imageUrl;
    
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    
    /**
     * Check if product is in stock
     */
    public boolean isInStock() {
        return stock != null && stock > 0;
    }
    
    /**
     * Check if requested quantity is available
     */
    public boolean hasStock(int quantity) {
        return stock != null && stock >= quantity;
    }
}
